### PR TITLE
split points and amount of recipes, removed placeholder

### LINKED ISSUE #115: Split points and amount of recipes, remove placeholder
Our finish screen should be more descriptive and calculate points correctly.

### PR DESCRIPTION
**Pull request by Astr042**
lab completed

### CODE REVIEW

**Comment by Astr042** [comment]
Do not delete branch, "next level" needs testing with additional levels and exit button ist currently not working.

**Review by JoeGre666 — CHANGES_REQUESTED** [review]
Looking better - still needs some improvement tho!
When you fail the first recipe, it will still count towards the failed recipe points - even tho it did not reduce points (because you can't get negative points)
Finish screen bug
We can either just remove the points for failed recipes or improve it.

**Comment by Astr042** [comment]
Should have the requested functionality now. Please re-review

**Review by JoeGre666 — APPROVED** [review]
Yes - good job, that's what I imagined :)

**Pull request merged**
